DEFAULT_SOURCE_CONFIGS = {
    "manual_mock": {
        "source_name": "manual_mock",
        "display_name": "Manual Mock",
        "description": "Safe mock source with deterministic sample jobs for local testing.",
        "source_type": "mock",
        "enabled": True,
        "runnable": True,
        "status": "active",
        "requires_api_key": False,
        "supports_auto_search": True,
        "fetches_external_url": False,
        "cooldown_minutes": 0,
        "last_run_at": None,
        "last_status": None,
        "last_error": None,
        "safety_level": "safe",
        "safety_notes": "Local mock data only. No external URL fetching, scraping, browser automation, or evasion.",
        "message": "",
    },
    "manual_import": {
        "source_name": "manual_import",
        "display_name": "Manual Import",
        "description": "Manual-only source for jobs pasted by the user.",
        "source_type": "manual",
        "enabled": True,
        "runnable": False,
        "status": "manual_only",
        "requires_api_key": False,
        "supports_auto_search": False,
        "fetches_external_url": False,
        "cooldown_minutes": 0,
        "last_run_at": None,
        "last_status": None,
        "last_error": None,
        "safety_level": "safe",
        "safety_notes": "Stores user-provided text only. It is not a runnable monitoring adapter.",
        "message": "Manual import is not a runnable source.",
    },
    "company_careers_placeholder": {
        "source_name": "company_careers_placeholder",
        "display_name": "Company Careers Placeholder",
        "description": "Placeholder for future company career-page adapters.",
        "source_type": "placeholder",
        "enabled": False,
        "runnable": False,
        "status": "not_implemented",
        "requires_api_key": False,
        "supports_auto_search": False,
        "fetches_external_url": False,
        "cooldown_minutes": 0,
        "last_run_at": None,
        "last_status": None,
        "last_error": None,
        "safety_level": "disabled",
        "safety_notes": "Not implemented in Phase 3A. No external requests are made.",
        "message": "Not implemented in Phase 3A.",
    },
    "techcareer_placeholder": {
        "source_name": "techcareer_placeholder",
        "display_name": "Techcareer Placeholder",
        "description": "Placeholder for a future Techcareer adapter.",
        "source_type": "placeholder",
        "enabled": False,
        "runnable": False,
        "status": "not_implemented",
        "requires_api_key": False,
        "supports_auto_search": False,
        "fetches_external_url": False,
        "cooldown_minutes": 0,
        "last_run_at": None,
        "last_status": None,
        "last_error": None,
        "safety_level": "disabled",
        "safety_notes": "Not implemented in Phase 3A. No external requests are made.",
        "message": "Not implemented in Phase 3A.",
    },
    "youthall_placeholder": {
        "source_name": "youthall_placeholder",
        "display_name": "Youthall Placeholder",
        "description": "Placeholder for a future Youthall adapter.",
        "source_type": "placeholder",
        "enabled": False,
        "runnable": False,
        "status": "not_implemented",
        "requires_api_key": False,
        "supports_auto_search": False,
        "fetches_external_url": False,
        "cooldown_minutes": 0,
        "last_run_at": None,
        "last_status": None,
        "last_error": None,
        "safety_level": "disabled",
        "safety_notes": "Not implemented in Phase 3A. No external requests are made.",
        "message": "Not implemented in Phase 3A.",
    },
    "linkedin_placeholder": {
        "source_name": "linkedin_placeholder",
        "display_name": "LinkedIn Placeholder",
        "description": "Placeholder for a future LinkedIn-safe integration review.",
        "source_type": "placeholder",
        "enabled": False,
        "runnable": False,
        "status": "not_implemented",
        "requires_api_key": False,
        "supports_auto_search": False,
        "fetches_external_url": False,
        "cooldown_minutes": 0,
        "last_run_at": None,
        "last_status": None,
        "last_error": None,
        "safety_level": "disabled",
        "safety_notes": "Not implemented in Phase 3A. No external requests are made.",
        "message": "Not implemented in Phase 3A.",
    },
    "kariyer_placeholder": {
        "source_name": "kariyer_placeholder",
        "display_name": "Kariyer.net Placeholder",
        "description": "Placeholder for a future Kariyer.net-safe integration review.",
        "source_type": "placeholder",
        "enabled": False,
        "runnable": False,
        "status": "not_implemented",
        "requires_api_key": False,
        "supports_auto_search": False,
        "fetches_external_url": False,
        "cooldown_minutes": 0,
        "last_run_at": None,
        "last_status": None,
        "last_error": None,
        "safety_level": "disabled",
        "safety_notes": "Not implemented in Phase 3A. No external requests are made.",
        "message": "Not implemented in Phase 3A.",
    },
}


def get_default_source_config(source_name: str) -> dict | None:
    config = DEFAULT_SOURCE_CONFIGS.get(source_name)
    return dict(config) if config else None

