import sys
from fpdf import FPDF
from datetime import datetime

class ReportPDF(FPDF):
    def __init__(self, title_text, footer_text):
        super().__init__()
        self.title_text = title_text
        self.footer_text = footer_text
        
    def header(self):
        self.set_font('helvetica', 'B', 15)
        self.cell(0, 10, self.title_text, border=0, ln=1, align='C')
        self.set_font('helvetica', 'I', 8)
        created_str = f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
        self.cell(0, 5, created_str, border=0, ln=1, align='C')
        self.ln(10)
        
    def footer(self):
        self.set_y(-15)
        self.set_font('helvetica', 'I', 8)
        self.cell(0, 10, f'{self.footer_text} | Page {self.page_no()}/{{nb}}', align='C')

def safe_pdf_text(text: str) -> str:
    translation_table = str.maketrans({
        'ğ': 'g', 'Ğ': 'G',
        'ı': 'i', 'İ': 'I',
        'ş': 's', 'Ş': 'S',
        'ç': 'c', 'Ç': 'C',
        'ö': 'o', 'Ö': 'O',
        'ü': 'u', 'Ü': 'U'
    })
    return text.translate(translation_table)

def create_pdf_bytes(title: str, content: str, is_turkish_ui: bool = True) -> bytes:
    footer_text = (
        "Job Application Assistant tarafindan olusturulmustur."
        if is_turkish_ui else
        "Generated by Job Application Assistant."
    )
    pdf = ReportPDF(safe_pdf_text(title), safe_pdf_text(footer_text))
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.set_font("helvetica", size=10)
    
    safe_content = safe_pdf_text(content)
    for line in safe_content.splitlines():
        pdf.multi_cell(0, 6, line)
        
    return bytes(pdf.output())

# Test it
try:
    content = "Merhaba, bu Turkce karakter iceren bir test metnidir: şığüöç ŞİĞÜÖÇ."
    pdf_bytes = create_pdf_bytes("Test Raporu", content, is_turkish_ui=True)
    print("PDF bytes length:", len(pdf_bytes))
    print("Success!")
except Exception as e:
    print("Error:", e)
    sys.exit(1)
